### ISSUE TITLE
Feature request: search news/article on frontend page

### ISSUE THREAD

**Issue by mysoundmagic** [luyadev/luya-module-news#32]
hello, Luya is very good I love it. I think there are features that should exist. maybe, features like frontend search, for searching news/article title, news/article category, and news/article with specific tags.

**Comment by nadar** [comment]
Hi @mysoundmagic 

We have a full page search module (LUYA Crawler), see here: https://github.com/luyadev/luya-module-crawler

A tag based search is currently not planned. Feel free to send a Pull Request or develop your own public LUYA Module.
