### ISSUE TITLE
Admin Menu Item

### ISSUE THREAD

**Issue by kayvin-my** [luyadev/luya-module-news#5]
Hi, after installing this module, the menu item for news is not appearing at the admin sidebar  like shown in the demo (block is showing though). Is this normal?

**Comment by nadar** [comment]
hi @kayvin-my have you checked your permission system after running import?

from the readme: 

> After adding the persmissions to your group you will be able to edit and add new news articles.

**Comment by kayvin-my** [comment]
It is exactly what i missed, you may close the issue now! Sorry bout that, im still exploring the Luya, and i have to say that you guys have done fantastically well in providing us such good kickstater for yii2. Thank you.

**Comment by nadar** [comment]
Good to know it works now. Thanks. Lets us know if you have any further questions or problems.

**Comment by Saraylu** [comment]
I logged as administrator into admin panel but the menu item don't appear in admin sidebar?

> (Administrator Accounts have full access to all Areas and can create, update and delete all data records.)

Your means from `After adding the persmissions to your group you will be able to edit and add new news articles.` is adding users to `administrator` group?

**Comment by nadar** [comment]
@msoa So you have installed the news module? Its not about adding a user to a group, its about open the permissions dialog and grant access to news module on the group where you are logged in.

<img width="1072" alt="bildschirmfoto 2018-09-01 um 23 02 09" src="https://user-images.githubusercontent.com/3417221/44949893-14332600-ae3b-11e8-86da-1412a32fa0c8.png">

grant the new permissions from news:

<img width="1320" alt="bildschirmfoto 2018-09-01 um 23 02 44" src="https://user-images.githubusercontent.com/3417221/44949899-27de8c80-ae3b-11e8-91a9-2373f6c2f17c.png">

Afterwards you should see the news module.

**Comment by Saraylu** [comment]
Yes i installed the module as Readme guide.
How can i access to 'open the permissions dialog' ?

**Comment by nadar** [comment]
@msoa Visit the groups section in the admin.

<img width="549" alt="bildschirmfoto 2018-09-01 um 23 09 11" src="https://user-images.githubusercontent.com/3417221/44949937-1a75d200-ae3c-11e8-9796-056595eaf0f5.png">

**Comment by Saraylu** [comment]
@nadar very thanks to take time for answering. Solved.

![screenshot 120](https://user-images.githubusercontent.com/2151566/44949993-397f5e80-ae52-11e8-8c25-c1a010fbc2d8.png)

**Comment by nadar** [comment]
Welcome. Enjoy LUYA!
